name: minecraft_mods_sync
description: A quick script that help you update your mods/mod-pack to all the players in efficent and simple way
version: 0.0.1
repository: https://github.com/freshplatform/mc-mods-sync

environment:
  sdk: ^3.2.6

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.2
